### ISSUE TITLE
Not working in JupyterLab or Visual Studio Code (only in hosted Jupyter Notebook)

### ISSUE THREAD

**Issue by opoloko** [kafonek/ipython_blocking#5] opened 2020-05-19 22:13 UTC
I find this module super useful, very elegant and quick solution, but can't get it to work in Jupyter Lab (<IPython.core.display.Javascript object> error in console) or Visual Studio Code (no errors).

Do you have any clue what I could try?

**Comment by kafonek** [comment] 2020-05-20 00:00
@opoloko thanks for flagging this, I haven't done any extensive testing with JupyterLab or VSCode.  After a bit of cursory fiddling this evening, I'm leaning towards the issue being with magic commands (`%block`, `%blockrun`) working differently in JupyterLab / VSCode versus classic Notebook.

I was able to get this minimal example to work with expected behavior in Jupyterlab:

```python
### cell 1
import ipywidgets as widgets

dropdown = widgets.Dropdown(options=['', 'foo', 'bar', 'baz'])
dropdown

### cell 2
import ipython_blocking
ctx = ipython_blocking.CaptureExecution()
with ctx:     
    while True:
        if dropdown.value:
            break
        ctx.step()

### cell 3
print("just a string to demonstrate blocking until dropdown changes")

### cell 4
print(dropdown.value)
```

After a cell -> run all, cells 3 and 4 didn't execute until after I chose an option in the dropdown widget.  

I haven't spent a lot of time looking at IPython magic commands outside of classic Notebook.  If you have any leads on the differences between classic vs Lab/VSCode, I'd appreciate pointers.  Thanks.

**Comment by bryceschober** [comment] 2020-10-02 00:01
Me too, FWIW...

**Comment by kafonek** [comment] 2020-10-02 01:45
@bryceschober I'm afraid I'm having trouble replicating these errors.  I just ran the 4-cell example code in both a VSCode (centos7 / python 3.6 / VSCode Python extension) and JupyterLab (Lab 2.2.5, using docker-stacks image, installed @jupyter-widgets from extension manager).  

Can you give any more details about system or versions that aren't working for you?  Thanks.

**Comment by bryceschober** [comment] 2020-10-02 19:28
@kafonek Hey, I guess you're right. I must have been doing something else wrong, because I switched a separate notebook to `%block dropdown` and it does work... You can go ahead and close this case.

**Closed as completed** 2020-10-07 12:51 UTC
